"""Task-oriented query routing for consumer-brand content operations.

The router is intentionally deterministic. It uses a small business graph to
map operational intents to preferred document types, focus terms, evidence
requirements, and compact query rewrites before the existing Hybrid Search
pipeline runs.
"""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, Iterable, List, Mapping


BUSINESS_INTENTS = {
    "product_verification",
    "brief_generation",
    "topic_ideation",
    "script_compliance",
    "review_optimization",
    "general",
}


@dataclass(frozen=True)
class RetrievalProfile:
    """Retrieval hints generated by task routing.

    These hints are metadata for the caller and future tuning. V1 does not hard
    override HybridSearch internals with them because the current collection
    metadata may not reliably contain document-type labels.
    """

    dense_top_k: int
    sparse_top_k: int
    fusion_top_k: int
    rerank_preferred: bool = True

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class BusinessGraphNode:
    """A lightweight business graph node for one content-ops task."""

    intent: str
    label: str
    keywords: List[str]
    preferred_doc_types: List[str]
    focus_terms: List[str]
    evidence_requirements: List[str]
    retrieval_profile: RetrievalProfile
    related_intents: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data["retrieval_profile"] = self.retrieval_profile.to_dict()
        return data


@dataclass(frozen=True)
class QueryRouteDecision:
    """Routing result used by query_knowledge_hub."""

    original_query: str
    rewritten_query: str
    intent: str
    intent_label: str
    confidence: float
    matched_terms: List[str]
    preferred_doc_types: List[str]
    focus_terms: List[str]
    evidence_requirements: List[str]
    retrieval_profile: RetrievalProfile

    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data["retrieval_profile"] = self.retrieval_profile.to_dict()
        return data


def _dedupe(items: Iterable[str]) -> List[str]:
    seen = set()
    result = []
    for item in items:
        key = item.lower()
        if key in seen:
            continue
        seen.add(key)
        result.append(item)
    return result


def default_business_graph() -> Dict[str, BusinessGraphNode]:
    """Return the default lightweight graph for content-operations retrieval."""

    return {
        "product_verification": BusinessGraphNode(
            intent="product_verification",
            label="product information verification",
            keywords=[
                "产品",
                "参数",
                "卖点",
                "成分",
                "规格",
                "功效",
                "价格",
                "核查",
                "准确",
                "真实性",
                "信息",
                "claim",
                "product",
                "spec",
            ],
            preferred_doc_types=["product_material", "brand_guideline"],
            focus_terms=["产品资料", "产品卖点", "参数核查", "功效宣称"],
            evidence_requirements=["cite_product_source", "avoid_unsupported_claims"],
            retrieval_profile=RetrievalProfile(24, 24, 12, True),
        ),
        "brief_generation": BusinessGraphNode(
            intent="brief_generation",
            label="brief generation",
            keywords=[
                "brief",
                "简报",
                "投放",
                "需求",
                "创意",
                "campaign",
                "达人",
                "种草",
                "生成",
                "方案",
            ],
            preferred_doc_types=["product_material", "brand_guideline", "script_template"],
            focus_terms=["内容brief", "投放目标", "产品卖点", "品牌调性"],
            evidence_requirements=["cite_product_source", "cite_brand_rule"],
            retrieval_profile=RetrievalProfile(24, 18, 12, True),
        ),
        "topic_ideation": BusinessGraphNode(
            intent="topic_ideation",
            label="content topic ideation",
            keywords=[
                "选题",
                "主题",
                "内容方向",
                "话题",
                "小红书",
                "抖音",
                "灵感",
                "爆款",
                "种草",
                "栏目",
                "创意",
            ],
            preferred_doc_types=["historical_review", "script_template", "product_material"],
            focus_terms=["历史复盘", "内容选题", "脚本模板", "产品卖点"],
            evidence_requirements=["compare_historical_review", "cite_reusable_template"],
            retrieval_profile=RetrievalProfile(26, 16, 12, True),
        ),
        "script_compliance": BusinessGraphNode(
            intent="script_compliance",
            label="script compliance",
            keywords=[
                "脚本",
                "合规",
                "品牌规范",
                "违规",
                "风险",
                "审核",
                "禁用词",
                "夸大",
                "宣称",
                "能不能说",
                "是否违反",
                "compliance",
                "risk",
            ],
            preferred_doc_types=["brand_guideline", "script_template", "product_material"],
            focus_terms=["品牌规范", "合规风险", "禁用表达", "修改建议"],
            evidence_requirements=["cite_brand_rule", "list_risk_points", "suggest_revision"],
            retrieval_profile=RetrievalProfile(18, 28, 12, True),
        ),
        "review_optimization": BusinessGraphNode(
            intent="review_optimization",
            label="post-campaign review optimization",
            keywords=[
                "复盘",
                "优化",
                "转化",
                "点击",
                "投放效果",
                "表现",
                "原因",
                "归因",
                "历史",
                "活动",
                "review",
                "conversion",
            ],
            preferred_doc_types=["historical_review", "script_template", "product_material"],
            focus_terms=["历史复盘", "转化表现", "优化建议", "可复用经验"],
            evidence_requirements=["compare_historical_review", "cite_prior_case"],
            retrieval_profile=RetrievalProfile(28, 18, 12, True),
        ),
    }


class TaskQueryRouter:
    """Classify content-ops task intent and rewrite query for retrieval."""

    def __init__(
        self,
        graph: Mapping[str, BusinessGraphNode] | None = None,
        min_confidence: float = 0.18,
    ) -> None:
        self.graph = dict(graph or default_business_graph())
        self.min_confidence = min_confidence

    def route(self, query: str) -> QueryRouteDecision:
        """Classify and rewrite a user query.

        Args:
            query: Original user query.

        Returns:
            Deterministic route decision. Empty queries route to general.
        """
        original = query or ""
        normalized = self._normalize(original)
        if not normalized:
            return self._general(original)

        scored = [
            (intent, *self._score_node(normalized, node))
            for intent, node in self.graph.items()
        ]
        scored.sort(key=lambda item: (item[1], len(item[2])), reverse=True)
        best_intent, best_score, matched_terms = scored[0]
        total_score = sum(item[1] for item in scored)
        confidence = best_score / max(1.0, total_score + 1.0)

        if best_score <= 0 or confidence < self.min_confidence:
            return self._general(original)

        node = self.graph[best_intent]
        return QueryRouteDecision(
            original_query=original,
            rewritten_query=self._rewrite(original, node),
            intent=node.intent,
            intent_label=node.label,
            confidence=round(confidence, 4),
            matched_terms=matched_terms,
            preferred_doc_types=list(node.preferred_doc_types),
            focus_terms=list(node.focus_terms),
            evidence_requirements=list(node.evidence_requirements),
            retrieval_profile=node.retrieval_profile,
        )

    @staticmethod
    def _normalize(query: str) -> str:
        return " ".join(query.strip().lower().split())

    @staticmethod
    def _score_node(query: str, node: BusinessGraphNode) -> tuple[float, List[str]]:
        score = 0.0
        matched = []
        for keyword in node.keywords:
            keyword_norm = keyword.lower()
            if not keyword_norm:
                continue
            if keyword_norm in query:
                matched.append(keyword)
                score += 2.0 if len(keyword_norm) > 1 else 1.0

        # Extra phrase-aware boosts for common mixed task queries.
        if node.intent == "script_compliance" and re.search(r"脚本.*(合规|风险|品牌规范|违规)", query):
            score += 3.0
        if node.intent == "product_verification" and re.search(r"产品.*(核查|准确|参数|卖点)", query):
            score += 3.0
        if node.intent == "review_optimization" and re.search(r"(复盘|历史).*(优化|转化|原因)", query):
            score += 3.0

        return score, _dedupe(matched)

    def _general(self, query: str) -> QueryRouteDecision:
        profile = RetrievalProfile(20, 20, 10, True)
        return QueryRouteDecision(
            original_query=query,
            rewritten_query=query,
            intent="general",
            intent_label="general knowledge retrieval",
            confidence=0.0,
            matched_terms=[],
            preferred_doc_types=[],
            focus_terms=[],
            evidence_requirements=["cite_sources"],
            retrieval_profile=profile,
        )

    @staticmethod
    def _rewrite(query: str, node: BusinessGraphNode) -> str:
        parts = [
            query.strip(),
            f"业务场景:{node.label}",
            f"优先资料:{' '.join(node.preferred_doc_types)}",
            f"关注点:{' '.join(node.focus_terms)}",
            f"证据要求:{' '.join(node.evidence_requirements)}",
        ]
        return "\n".join(part for part in parts if part)
